### ISSUE TITLE
feat: badger subgraph support via graphql library

### ISSUE THREAD

**Issue by axejintao** [Badger-Finance/badger-sdk#46]
# Background

Similar to the way the SDK implements the API interface for easily querying data from our implementation, the SDK should also support querying directly the subgraphs that Badger maintains to do whatever data analysis they wish. The GraphQL support should follow the same pattern as the API support. It should be able to be a stand alone usage while also available within the SDK itself. 

The SDK is a general purpose tool that will implement all methods of data retrieval for information Badger offers as well as implement a select set of user functionality. The easy of querying the Badger subgraph fits into this goal.

The ideal example of how to integrate this is available in the [API GraphQL Configuration](https://github.com/Badger-Finance/badger-api/blob/main/codegen.yml).

## Tasks

- [x] Add GraphQL, queries, fragments, and configuration
- [x] Add BadgerGraph support as stand alone and sdk offering
- [x] Add test coverage where possible / applicable
