### ISSUE TITLE
[feat]: @badger-dao/sdk-mocks lib for testing

### ISSUE THREAD

**Issue by NamelsKing** [Badger-Finance/badger-sdk#74]
# Background

To provide convenient unit testing with our sdk, gather responses from onchain and offchain data in separate deployed mocks lib.
As sdk goals to become main fetching point of badger data, it would be easy to mock this resp and use such tools as snapshot testing, to keep ur services coverage at high lvl.

## Tasks

- [x] Write mocks processor, that will cover all sdk methods.
- [x] Save responses to .json files, for easy imports
- [x] Export .json files in one entry, pack as a lib
- [ ] Deploy with `semantic-release-bot` (should be synced with main lib)
